### ISSUE TITLE
Card wrapping uneven

### ISSUE THREAD

**Issue by mhowe21** [KolbyLaw/What-to-Watch#8]
## Summary: 
When Secondary selection movie cards are uneven in size, the cards can fail to wrap correctly. 

### User Expected Behavior:
As a user when I search for multiple additional options for a movie, the layout should be even and visually appealing. 

### Example Screenshots:
Example 1:
![cardWrapping2](https://user-images.githubusercontent.com/48158483/103486399-d81d8080-4dba-11eb-8bae-658904a328d6.png)

Example 2:
![cardWrapping](https://user-images.githubusercontent.com/48158483/103486400-d9e74400-4dba-11eb-8775-455bf1457ab0.png)

**Comment by KolbyLaw** [comment]
Temporarily closing this issue - consolidating with a new issue ticket.
